- name: Install Tmux
  apt:
    name: tmux

- name: Install xclip
  apt:
    name: xclip

- name: Setup Tmux
  become_user: "{{user}}"
  copy:
    src: tasks/apps/tmux/.tmux.conf
    dest: /home/{{user}}/
    
- name: Creates directory
  become_user: "{{user}}"
  file:
    path: /home/{{user}}/.tmux/plugins/tpm
    state: directory

- name: Install Tmux Plugin Manager 
  become_user: "{{user}}"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/{{user}}/.tmux/plugins/tpm

- name: Reload Tmux 
  become_user: "{{user}}"
  command: tmux source /home/{{user}}/.tmux.conf
