- name: Install aws cli dependencies
  apt: name={{item}}
  with_items:
    - python-dev
  ignore_errors: yes

- name: Create temporary dir
  tempfile:
    state: directory
    suffix: -aws-cli
  register: temp_dir

- debug:
    msg: "Temp Dir: {{temp_dir}}"

- name: Unpack aws cli archive
  unarchive:
    src: "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
    dest: "{{temp_dir.path}}"
    remote_src: true

- name: Install aws cli 
  command: "{{temp_dir.path}}/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws"

- name: Removing temporary dir
  file:
    path: "{{temp_dir.path}}"
    state: absent
