- name: Install TLP
  become: true
  apt:
    name: tlp

- name: Configure TLP
  become: true
  copy:
    src: tasks/system/tlp
    dest: /etc/default

- name: Install Powertop
  become: true
  apt:
    name: powertop

- name: Set monitor refresh rate
  become_user: "{{user}}"
  copy:
    src: tasks/system/monitors.xml
    dest: /home/{{user}}/.config