- name: Install Vim
  apt:
    name: vim

- name: Creates Vim directory
  become_user: "{{user}}"
  file: 
    path: /home/{{user}}/.vim
    state: directory

- name: Install Vundle Package Manager
  become_user: "{{user}}"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/{{user}}/.vim/bundle/Vundle.vim

- name: Setup Vim
  become_user: "{{user}}"
  copy:
    src: tasks/apps/vim/.vimrc
    dest: /home/{{user}}/
